plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
}

// Ensure the dependencies are shared
dependencies {
    compileOnly "org.spongepowered:mixin:0.8.5"
    compileOnly "io.github.llamalad7:mixinextras-common:0.3.5"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.5"
    compileOnly "org.projectlombok:lombok:1.18.44"
    annotationProcessor "org.projectlombok:lombok:1.18.44"
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:26.1.154"
}

sourceSets {
    main {
        // Standard main source set
    }
    client {
        java.srcDir 'src/client/java'
        resources.srcDir 'src/client/resources'
        // Allow client to see main
        compileClasspath += sourceSets.main.compileClasspath + sourceSets.main.output
        runtimeClasspath += sourceSets.main.runtimeClasspath + sourceSets.main.output
    }
}



configurations {
    clientImplementation.extendsFrom(implementation)
    clientCompileOnly.extendsFrom(compileOnly)
    clientAnnotationProcessor.extendsFrom(annotationProcessor)
    clientRuntimeOnly.extendsFrom(runtimeOnly)

    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    commonClientJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonClientResources {
        canBeResolved = false
        canBeConsumed = true
    }
}


artifacts {
    // This points the loaders to the actual source files in common
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
    commonClientJava sourceSets.client.java.sourceDirectories.singleFile
    commonClientResources sourceSets.client.resources.sourceDirectories.singleFile
}

// Standard multi-loader attribute logic
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}


